steps:
- id: "build docker image"
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/${REPO}/dwn-server-gcp:v0.2.2', '.' ]
- id: "push docker image"
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/${REPO}/dwn-server-gcp:v0.2.2' ]
- id: "deploy to cloud run"
  name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'dwn-server-gcp'
  - '--image'
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/${REPO}/dwn-server-gcp:v0.2.2'
  - '--port'
  - '3000'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--add-cloudsql-instances'
  - '${PROJECT_ID}:us-central1:{database}'
  - '--set-env-vars'
  - 'DWN_GCS_BUCKET_NAME={bucket_name},DWN_STORAGE=postgres:///dwn,PGHOST={connection_path},PGDATABASE={database},PGUSER={db_user},PGPASSWORD={db_pwd}},DWN_REGISTRATION_PROOF_OF_WORK_ENABLED=true,DWN_TERMS_OF_SERVICE_FILE_PATH=/dwn-server/TOS.txt'
  - '--allow-unauthenticated'